# Generated by Django 5.0.1 on 2024-01-24 02:14

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='address',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('e', 'employee'), ('c', 'customer'), ('m', 'manager')], default='c', max_length=1),
        ),
    ]
