# Generated by Django 5.0.1 on 2024-01-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='color',
        ),
        migrations.AddField(
            model_name='attribute',
            name='code_color',
            field=models.CharField(default='', max_length=20, verbose_name='code color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_color',
            field=models.CharField(default=1, max_length=20, verbose_name='name color'),
            preserve_default=False,
        ),
    ]
